# Generated by Django 3.2.9 on 2021-11-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.CharField(max_length=255)),
                ('openid', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=255, null=True)),
                ('birthyear', models.CharField(blank=True, max_length=255, null=True)),
                ('illtime', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('surgerytime', models.CharField(blank=True, db_column='surgeryTime', max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('illtype', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'healthinfo',
                'managed': False,
            },
        ),
    ]
