# Generated by Django 3.2.9 on 2021-11-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_authtable_healthinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'record_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'total_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TranData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tran_data',
                'managed': False,
            },
        ),
    ]
