# Generated by Django 3.2.9 on 2021-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_recorddata_totaldata_trandata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'file_storage',
                'managed': False,
            },
        ),
    ]
