# Generated by Django 3.2.9 on 2023-04-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20211222_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'game_score',
                'managed': False,
            },
        ),
    ]

"""
CREATE TABLE game_score (
    id bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
    phone varchar(255),
    score integer,
    time varchar(255)
);

INSERT INTO game_score (phone, score, time) VALUES ('12345678911', 90, '2022-04-11');
INSERT INTO game_score (phone, score, time) VALUES ('12345678911', 100, '2022-04-11');
INSERT INTO game_score (phone, score, time) VALUES ('12345671234', 90, '2022-04-11');
INSERT INTO game_score (phone, score, time) VALUES ('12345671234', 100, '2022-04-10');
INSERT INTO game_score (phone, score, time) VALUES ('12345671234', 90, '2022-04-11');
INSERT INTO game_score (phone, score, time) VALUES ('12345673234', 123, '2022-04-11 20:00:00');
INSERT INTO game_score (phone, score, time) VALUES ('12345623455', 90, '2022-04-11');
INSERT INTO game_score (phone, score, time) VALUES ('12342342357', 90, '2022-04-12');
INSERT INTO game_score (phone, score, time) VALUES ('12342424567', 90, '2022-04-14');
INSERT INTO game_score (phone, score, time) VALUES ('12425234567', 90, '2022-04-11');
INSERT INTO game_score (phone, score, time) VALUES ('12453234567', 123, '2022-04-11 23:11:23');
INSERT INTO game_score (phone, score, time) VALUES ('12453234567', 134, '2022-04-11');
INSERT INTO game_score (phone, score, time) VALUES ('12453234567', 90, '2022-04-11');
INSERT INTO game_score (phone, score, time) VALUES ('12345454567', 90, '2022-04-11');
INSERT INTO game_score (phone, score, time) VALUES ('12345678967', 90, '2022-04-11');
INSERT INTO game_score (phone, score, time) VALUES ('12345775667', 90, '2022-04-11');

"""