# Generated by Django 3.2.9 on 2023-04-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20211222_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'game_score',
                'managed': False,
            },
        ),
    ]

"""
CREATE TABLE game_score (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    phone varchar(255),
    score integer,
    time varchar(255)
);
"""